- src/containers/product/image-previews.svelte
- src/containers/product/item-content.svelte
- src/routes/product/[id([0-9]+)]/index.svelte
> Fix the purchase count and selected color synchronization

- src/components/ui/date-picker.svelte
- src/components/ui/time-picker.svelte
- src/containers/ui/date-pickers.svelte
- src/containers/ui/time-pickers.svelte
- src/routes/ui.svelte
- static/css/global/src/ui-kit.scss
- static/css/global/ui-kit.css
Will implement a calendar for picking a date and a date range, as well as a simple spinner-based time picker. Both can be seen in the UI kit page
> Date and time pickers

- Dockerfile
- Dockerfile.prod
> Update Dockerfile to use node:13-alpine and yarn

- src/constants/store/order.js
> Flip product ordering by time

- src/routes/profile.svelte
> Implement leaving feedback from profile

- src/routes/profile.svelte
- static/css/global/common.css
- static/css/global/src/common.scss
- static/css/page-components/header.css
- static/css/page-components/src/header.scss
> Force the footer to stick to the bottom of the page

- src/routes/store.svelte
> Reset pagination upon filter changes

- src/components/projects/new/project-image-picker.svelte
- src/constants/projects/order.js
- src/containers/projects/view/project-header.svelte
- src/routes/projects/[id([0-9]+)]/edit.svelte
- static/css/edit-project/main.css
- static/css/edit-project/src/main.scss
- static/css/view-project/main.css
- static/css/view-project/src/main.scss
> Edit project

- src/routes/projects/[id([0-9]+)]/index.svelte
This looks good to me, probably should be merged and forgotten
> Don't crash if user is unauthenticated

- src/components/projects/view/application-hour-tile.svelte
- src/components/projects/view/application-tile.svelte
- src/components/projects/view/feedback-tile.svelte
- src/components/projects/view/report-performance-modal.svelte
- src/containers/home/contacts.svelte
> Force the t.me links to open in new tabs

- src/components/ui/autocomplete.svelte
- src/containers/dashboard/innopoint-transfer.svelte
- src/containers/projects/new/step-3.svelte
> Add leading placeholders to people autocompletes

- src/server.js
For whatever reasons it tries to download fonts, we'll let it
> Allow the service worker to access gstatic for fonts

- src/components/projects/view/application-dialog.svelte
- src/routes/projects/[id([0-9]+)]/index.svelte
> Unconditionally remember telegram username

- src/components/common/image-resizer.svelte
- src/components/projects/new/project-image-picker.svelte
- src/components/projects/view/moderator-hour-card.svelte
- src/containers/projects/new/step-1.svelte
- src/routes/projects/new.svelte
> Disable the button while uploading image

- src/components/projects/view/application-hour-tile.svelte
- src/components/projects/view/hour-activity-card.svelte
- src/components/projects/view/report-performance-modal.svelte
- src/containers/projects/new/step-2.svelte
- src/containers/projects/view/moderator-view.svelte
- src/routes/projects/[id([0-9]+)]/index.svelte
- src/routes/projects/new.svelte
Closes #206 
Upd: and accidentally also closes #211
> Scroll the duplicated activities into view automatically

- src/components/projects/new/edit-activity.svelte
- src/containers/products/edit-form.svelte
- src/containers/projects/new/step-1.svelte
- src/containers/projects/view/moderator-hour-panel.svelte
- src/routes/products/[id([0-9]+)]/edit.svelte
- src/routes/products/new.svelte
- src/routes/projects/[id([0-9]+)]/edit.svelte
- src/routes/projects/new.svelte
- src/utils/space-only.js
Closes #236 
Will also rename the Moderation internal activity to `[[Moderation]]`, because I figured that in some cases people would wanna create the Moderation activity for themselves, so to avoid collisions I added symbols.
> Prohibit whitespace-only names

- src/components/products/drag-dropzone.svelte
Fixes the issue where you upload a file, then remove it, and no longer can upload that same file.
> Clear the input value to not mess with the dropzone

- src/components/dashboard/purchase-card.svelte
- src/containers/dashboard/purchases.svelte
> Allow undoing marks as rejected or delivered

- src/components/common/notification-center.svelte
- src/constants/backend/notification-types.js
- src/constants/env.js
- src/constants/notification-content.js
- src/routes/store.svelte
Closes #167, closes #99 
UPD: we do have to write "closes" twice
> Implement new arrivals and auto-dismissing the notification

- src/components/profile/reclaim-innopoints-modal.svelte
- src/routes/profile.svelte
> Update the labels allowing usernames to reclaim innopoints

- src/components/projects/new/people-selector.svelte
- src/containers/products/item-content.svelte
Fixes #154
Bonus: fixes #243 as well
> Change selected variety when changing color

- package.json
- rollup.config.js
- src/components/dashboard/purchase-card.svelte
- src/components/projects/new/project-image-picker.svelte
- src/containers/projects/tagline.svelte
- src/containers/projects/view/project-header.svelte
- yarn.lock
Finally they got their shit together and we can bump dependencies
> Bump dependencies

- src/components/products/new/draft-restore-notice.svelte
- src/routes/products/new.svelte
- static/css/components/products/new/draft-restore-notice.scss
> Set up product persistence

- src/components/products/new/color-picker.svelte
> Allow clearing the color selection

- src/components/dashboard/past-purchase-tile.svelte
- src/components/dashboard/purchase-list-modal.svelte
- src/components/products/view/purchase-modal.svelte
- src/containers/dashboard/purchases.svelte
- static/css/components/dashboard/past-purchase-tile.scss
- static/css/components/dashboard/purchase-list-modal.scss
> Purchase history

- src/containers/errors/error-404.svelte
> Randomize the link in the 404 page

- package.json
- src/components/common/multi-image-resizer.svelte
- src/components/products/new/image-input.svelte
- src/components/products/new/image-tile.svelte
- static/css/components/common/multi-image-resizer.scss
- yarn.lock
Phew, that was messy. Test this one carefully.
Closes #262
Closes #134
> Implement the resizing dialog for several images

- src/components/products/view/purchase-modal.svelte
- src/containers/products/view/item-content.svelte
- src/routes/products/[id([0-9]+)]/index.svelte
> Fix the reset of the selected variety

- src/routes/products/[id([0-9]+)]/edit.svelte
> Ensure the deletion requests are run after creation requests

- src/routes/projects/[id([0-9]+)]/index.svelte
Redirect to "create project" page instead
> Prevent viewing a draft project

- package.json
- yarn.lock
Also remedies a security vulnerability
> Bump the dependencies

- src/constants/home/options.js
Closes #282 
Other links seem fine
> Update the link to the buddy program

- src/template.html
- static/css/_attractions-theme.scss
- static/css/common.scss
- static/css/components/footer.scss
- static/css/components/header.scss
- static/css/components/home/option-step.scss
- static/css/components/projects/view/moderated-activity.scss
- static/css/components/projects/view/user-activity-card.scss
- static/css/containers/home/how-to.scss
- static/css/containers/home/tagline.scss
> Replace the fonts for the guideline ones

- src/components/projects/view/application-hour-tile.svelte
- src/components/projects/view/finalizing-activity-card.svelte
- src/routes/projects/[id([0-9]+)]/index.svelte
Closes #291 
Also fixes that nonsense with trying to serialize a store, which was breaking our SSR
> Ensure the changed hours are shown after leaving the report

- src/components/projects/view/application-hour-tile.svelte
- src/containers/projects/view/moderator-view.svelte
Check out the last commit, please. It's not directly related to the issue but something was odd there and I changed it without testing, so I need a sanity check
> Bug report: cannot set zero hours for volunteers in the finalizing stage

- src/components/footer.svelte
- yarn.lock
As per the external requests. About the dependencies — I have no clue if it's gonna work, let's just hope it does.
> Make some changes to the footer
